language: node_js
node_js:
  - "11"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  fqdn: $GITHUB_PAGES_CUSTOM_DOMAIN
  keep_history: true
  on:
    branch: master
  local_dir: public
